In [ ]:
#import panda, numpy, matplotlib libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Dataset importation 
unemployment = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/country_total.csv')

In [ ]:
#Type of "unemployment", it is a dataframe
type(unemployment)

pandas.DataFrame

In [ ]:
#To see the first 5 rows of the data frame
unemployment.head()

  country seasonality    month  unemployment  unemployment_rate
0      at         nsa  1993.01        171000                4.5
1      at         nsa  1993.02        175000                4.6
2      at         nsa  1993.03        166000                4.4
3      at         nsa  1993.04        157000                4.1
4      at         nsa  1993.05        147000                3.9

In [ ]:
#To see the quantity of columns and rows in the dataset
unemployment.shape

(20796, 5)

In [ ]:
#To see all the columns (including its names) of the dataframe
unemployment.columns

Index(['country', 'seasonality', 'month', 'unemployment', 'unemployment_rate'], dtype='str')

In [ ]:
#To see the type of data of each columns
unemployment.dtypes

country                  str
seasonality              str
month                float64
unemployment           int64
unemployment_rate    float64
dtype: object

In [ ]:
#To see a summarized statistics view of the dataframe
unemployment.describe

<bound method NDFrame.describe of       country seasonality    month  unemployment  unemployment_rate
0          at         nsa  1993.01        171000                4.5
1          at         nsa  1993.02        175000                4.6
2          at         nsa  1993.03        166000                4.4
3          at         nsa  1993.04        157000                4.1
4          at         nsa  1993.05        147000                3.9
...       ...         ...      ...           ...                ...
20791      uk       trend  2010.06       2429000                7.7
20792      uk       trend  2010.07       2422000                7.7
20793      uk       trend  2010.08       2429000                7.7
20794      uk       trend  2010.09       2447000                7.8
20795      uk       trend  2010.10       2455000                7.8

[20796 rows x 5 columns]>

In [ ]:
#Creation of an array
my_list = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
#Print of the last 4 elements of the array
my_list[len(my_list)-4:]

['c', 'd', 'e', 'f']

In [ ]:
#Importation of countries.csv dataset
countries = pd.read_csv('/workspaces/Machine-Learning-6-SIN-A-Mar-Jul-2026/data/countries.csv')

In [ ]:
countries.shape

(30, 8)

In [22]:
countries.columns

Index(['country', 'google_country_code', 'country_group', 'name_en', 'name_fr',
       'name_de', 'latitude', 'longitude'],
      dtype='str')

In [25]:
countries.head()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
0,at,AT,eu,Austria,Autriche,Österreich,47.696554,13.345980
1,be,BE,eu,Belgium,Belgique,Belgien,50.501045,4.476674
2,bg,BG,eu,Bulgaria,Bulgarie,Bulgarien,42.725674,25.482322
3,hr,HR,non-eu,Croatia,Croatie,Kroatien,44.746643,15.340844
4,cy,CY,eu,Cyprus,Chypre,Zypern,35.129141,33.428682

In [26]:
countries.tail()

,country,google_country_code,country_group,name_en,name_fr,name_de,latitude,longitude
25,si,SI,eu,Slovenia,Slovénie,Slowenien,46.149259,14.986617
26,es,ES,eu,Spain,Espagne,Spanien,39.895013,-2.988296
27,se,SE,eu,Sweden,Suède,Schweden,62.198467,14.896307
28,tr,TR,non-eu,Turkey,Turquie,Türkei,38.952942,35.439795
29,uk,GB,eu,United Kingdom,Royaume-Uni,Vereinigtes Königreich,54.315447,-2.232612

In [27]:
countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              30 non-null     str
 1   google_country_code  30 non-null     str
 2   country_group        30 non-null     str
 3   name_en              30 non-null     str
 4   name_fr              30 non-null     str
 5   name_de              30 non-null     str
 6   latitude             30 non-null     float64
 7   longitude            30 non-null     float64
dtypes: float64(2), str(6)
memory usage: 2.0 KB

In [29]:
countries.describe()

        latitude  longitude
count  30.000000  30.000000
mean   49.092609  14.324579
std     7.956624  11.257010
min    35.129141  -8.239122
25%    43.230916   6.979186
50%    49.238087  14.941462
75%    54.090400  23.351690
max    64.950159  35.439795